<?=$this->form()->openTag($form);?>

    <div class="form-group">
        <?=$this->formLabel($form->get('username'));?>
        <div class="col-sm-10">
            <?=$this->formText($form->get('username'));?>
            <?=$this->formElementErrors($form->get('username'));?>
        </div>
    </div>

    <div class="form-group">
        <?=$this->formLabel($form->get('password'));?>
        <div class="col-sm-10">
            <?=$this->formText($form->get('password'));?>
            <?=$this->formElementErrors($form->get('password'));?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?=$this->formSubmit($form->get('submit'));?>
        </div>
    </div>

<?=$this->form()->closeTag($form);?>